### PR TITLE
Repeat letters bug

### LINKED ISSUE #2: Repeat letters bug
If you guess the same letter twice in a word, but the word only has that letter once, wordle will show the second instance as not present.   If you mirror this in worldehelper and mark the same letter as Present and also Not present then you will get no results.

### PR DESCRIPTION
**Pull request by JAKONL**

### CODE REVIEW

File: poc2/public/script/wordlehelper.js [hunk 1]
```diff
@@ -393,21 +393,15 @@ $(document).ready(function(){
...
       {
-      console.log("Removing present letters from non-present letters")
+      console.log("Removing present and correct letters from non-present letters")
         //remove present letters from the not-present letters
         arrPresentLettersSet = new Set(arrPresentLetters);
+        arrCorrectLettersSet = new Set(arrCorrectLetters);
+        arrPresentAndCorrectLettersSet = new Set([...arrPresentLettersSet, ...arrCorrectLettersSet]);
         arrNotPresentLetters = arrNotPresentLetters.filter( (x) => {
-          return !arrPresentLettersSet.has(x);
+          return !arrPresentAndCorrectLettersSet.has(x);
```
Comment (droobilicious) [inline poc2/public/script/wordlehelper.js:404]: i would probably define this as something like
 return !(arrPresentLettersSet.has(x) || arrPresentAndCorrectLettersSet.has(x))

**Comment by droobilicious** [comment]
Reviewed and tested
